// Copyright 2017-2021 @5ire/api-contract authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@5ire/api-contract', version: '0.2.2' };
